using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;

public class DeathBlockScript : MonoBehaviour
{
    public GameObject player;
    public TMP_Text log;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.tag == "Player")
        {
            SceneManager.LoadScene(SceneManager.GetActiveScene().name);
        }
    }
}
